// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw3f379kc1N8bbpeHU8eZ5nQ3mldOmsR8',
    appId: '1:876381792726:web:e8e5ab8ea08a3f82929c77',
    messagingSenderId: '876381792726',
    projectId: 'cmsc23-project-group5',
    authDomain: 'cmsc23-project-group5.firebaseapp.com',
    storageBucket: 'cmsc23-project-group5.appspot.com',
    measurementId: 'G-EGYCPV1Z1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVW4cPjRE2T1SNIXjunfWo5fAK83bAndg',
    appId: '1:876381792726:android:848f17fb3e772fd9929c77',
    messagingSenderId: '876381792726',
    projectId: 'cmsc23-project-group5',
    storageBucket: 'cmsc23-project-group5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvnhwbzP1KTwWMyWLIWxSFH0zmrgMhruU',
    appId: '1:876381792726:ios:aa28841e0bc21d77929c77',
    messagingSenderId: '876381792726',
    projectId: 'cmsc23-project-group5',
    storageBucket: 'cmsc23-project-group5.appspot.com',
    iosClientId: '876381792726-1cl928aq8uip83pfbpo9gj2q2mc05fum.apps.googleusercontent.com',
    iosBundleId: 'com.example.safePass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvnhwbzP1KTwWMyWLIWxSFH0zmrgMhruU',
    appId: '1:876381792726:ios:aa28841e0bc21d77929c77',
    messagingSenderId: '876381792726',
    projectId: 'cmsc23-project-group5',
    storageBucket: 'cmsc23-project-group5.appspot.com',
    iosClientId: '876381792726-1cl928aq8uip83pfbpo9gj2q2mc05fum.apps.googleusercontent.com',
    iosBundleId: 'com.example.safePass',
  );
}
